AWS1G_MODEL = "AWS EC2"
AWS2G_MODEL = "Amazon AWS Cloud Provider 2G"
AWS_MODELS = [AWS1G_MODEL, AWS2G_MODEL]

SECRET_KEY_ATTRIBUTE = 'AWS Secret Access Key'
ACCESS_KEY_ATTRIBUTE = 'AWS Access Key ID'
