from __future__ import annotations


class TerraformDeploymentAppAttributeNames:
    git_token = "Git Token"
    git_terraform_url = "Git Terraform URL"
    branch = "Branch"
    terraform_inputs = "Terraform Inputs"
    terraform_sensitive_inputs = "Terraform Inputs"
    cloud_provider = "Cloud Provider"
    custom_tags = "Custom Tags"
    autogenerated_name = "Autogenerated Name"
