from __future__ import annotations

from cloudshell.cp.core.request_actions import DeployVMRequestActions
from cloudshell.cp.core.request_actions.models import DeployApp

from cloudshell.cp.terraform import constants
from cloudshell.cp.terraform.models.base_deployment_app import (
    TerraformDeploymentAppAttributeNames, ResourcePasswordAttrRODeploymentPath,
    ResourceAttrRODeploymentPath, ResourceDictAttrRODeploymentPath,
    ResourceDictPasswordAttrRODeploymentPath, ResourceBoolAttrRODeploymentPath
)


class VMFromTerraformGit(DeployApp):
    _DO_NOT_EDIT_APP_NAME = True
    ATTR_NAMES = TerraformDeploymentAppAttributeNames
    DEPLOYMENT_PATH = constants.VM_FROM_TF_GIT

    autogenerated_name: str = ResourceBoolAttrRODeploymentPath(
        ATTR_NAMES.autogenerated_name
    )
    branch: str = ResourceAttrRODeploymentPath(ATTR_NAMES.branch)
    cloud_provider: str = ResourceAttrRODeploymentPath(ATTR_NAMES.cloud_provider)
    custom_tags: dict[str: str] = ResourceDictAttrRODeploymentPath(
        ATTR_NAMES.custom_tags
    )
    git_terraform_url: str = ResourceAttrRODeploymentPath(ATTR_NAMES.git_terraform_url)
    git_token: str = ResourcePasswordAttrRODeploymentPath(ATTR_NAMES.git_token)
    terraform_inputs: dict[str: str] = ResourceDictAttrRODeploymentPath(
        ATTR_NAMES.terraform_inputs
    )
    terraform_sensitive_inputs: dict[str: str] = \
        ResourceDictPasswordAttrRODeploymentPath(ATTR_NAMES.terraform_sensitive_inputs)


class VMFromTerraformGitRequestActions(DeployVMRequestActions):
    deploy_app: VMFromTerraformGit
