from __future__ import annotations

from cloudshell.cp.core.request_actions import DeployVMRequestActions
from cloudshell.cp.core.request_actions.models import DeployApp
from cloudshell.shell.standards.core.resource_conf import attr

from cloudshell.cp.terraform.models.base_deployment_app import (
    TerraformDeploymentAppAttributeNames,
)


class VMFromTerraformGit(DeployApp):
    _DO_NOT_EDIT_APP_NAME = True
    ATTR_NAMES = TerraformDeploymentAppAttributeNames

    git_token: str = attr(ATTR_NAMES.git_token, is_password=True)
    git_terraform_url: str = attr(ATTR_NAMES.git_terraform_url)
    branch: str = attr(ATTR_NAMES.branch)
    terraform_inputs: str = attr(ATTR_NAMES.terraform_inputs)
    terraform_sensitive_inputs: str = attr(ATTR_NAMES.terraform_sensitive_inputs,
                                is_password=True)
    cloud_provider: str = attr(ATTR_NAMES.cloud_provider)
    autogenerated_name = attr(ATTR_NAMES.autogenerated_name)

    #remote_state_provider: str = attr(ATTR_NAMES.remote_state_provider)
    custom_tags: str = attr(ATTR_NAMES.custom_tags)


class VMFromTerraformGitRequestActions(DeployVMRequestActions):
    deploy_app: VMFromTerraformGit