tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: HashiCorp Terraform
  template_author: Quali
  template_version: 1.0.0
  template_icon: GitTerraform-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_1.yaml

node_types:
  vendor.resource.Terraform Resource From Git:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Cloud Provider Resource:
        description: "CloudShell cloud provider resource name to be used for 
        retrieving cloud provider credentials"
        type: string
        tags: [ user_input ]
      Git Terraform Module Path:
        description: "Git url to the Terraform module. Supports the same URL format from a browser. For Github, the entire repo will be downloaded. Url to a folder: https://github.com/ACCOUNT/REPO/tree/BRANCH/PATH_TO_FOLDER or url to a TF file: https://github.com/ACCOUNT/REPO/blob/BRANCH/PATH/filename.tf. Gitlab: 'http://<GITLAB_DOMAIN>/<USER>/<PROJECT_NAME>/-/tree/<BRANCH>/<FOLDER_PATH>'"
        type: string
        tags: [ user_input ]
      Terraform Inputs:
        # ToDo add json support
        # ToDo add tfvars support
        description: Semi-colon separated name=value list (e.g. varname1=varvalue1;varname2=varvalue2...)
        type: string
        tags: [ user_input ]
      Terraform Sensitive Inputs:
        # ToDo add json support
        description: Semi-colon separated name=value list (e.g. varname1=varvalue1;varname2=varvalue2...)
        type: cloudshell.datatypes.Password
        tags: [ user_input ]
      Terraform App Inputs Map:
        description: "Semi-colon separated name=value list (e.g. 
        terraform_input_var_name1=App Resource Attribute Name;
        terraform_input_var_name2=App Resource Attribute Name...)"
        type: string
        tags: [ user_input ]
      Terraform App Outputs Map:
        description: "Semi-colon separated name=value list (e.g. 
        terraform_output_var_name1=App Resource Attribute Name;
        terraform_output_var_name2=App Resource Attribute Name...). App Resource 
        Attributes Names 'app_name' and 'address' reserved for the address and name of 
        the deployed resource."
        type: string
        tags: [ user_input ]
      Branch:
        description: "Overrides the branch in the the Module URL."
        type: string
        tags: [ user_input ]
      Custom Tags:
        description: "Semi-colon separated name=value list (e.g. varname1=varvalue1;varname2=varvalue2...)"
        type: string
        tags: [ user_input ]
      Autogenerated Name:
        description: "If true the name would be generated by the Shell, otherwise it 
        would be the same as App name."
        type: boolean
        default: true
        tags: [ user_input ]
#      Remote State Provider:
#        description: Remote State provider resource name (only used if filled)
#        type: string
#        tags: [ user_input ]
    artifacts:
      icon:
        file: GitTerraform-icon.png
        type: tosca.artifacts.File
