from __future__ import annotations

from typing import TYPE_CHECKING

from cloudshell.cp.core.flows.deploy import AbstractDeployFlow
from cloudshell.cp.core.request_actions.models import (
    Attribute,
    DeployAppResult,
    VmDetailsData,
)
from cloudshell.cp.core.rollback import RollbackCommandsManager
from cloudshell.cp.core.utils.name_generator import NameGenerator

from cloudshell.cp.terraform.handlers.tf_handler import TerraformCPHandler
from cloudshell.cp.terraform.utils.cs_helpers import on_task_progress_check_if_cancelled
# from cloudshell.cp.terraform.utils.vm_console_link_attr import (
#     get_deploy_app_vm_console_link_attr,
# )
from cloudshell.iac.terraform.services.object_factory import ObjectFactory

if TYPE_CHECKING:
    from logging import Logger

    from cloudshell.api.cloudshell_api import CloudShellAPISession
    from cloudshell.cp.core.cancellation_manager import CancellationContextManager
    from cloudshell.cp.core.request_actions import DeployVMRequestActions
    from cloudshell.cp.core.reservation_info import ReservationInfo

    from cloudshell.cp.terraform.models.deploy_app import VMFromTerraformGit
    from cloudshell.cp.terraform.resource_config import TerraformResourceConfig


class TFDeployVMFlow(AbstractDeployFlow):
    def __init__(
        self,
        resource_config: TerraformResourceConfig,
        cs_api: CloudShellAPISession,
        reservation_info: ReservationInfo,
        cancellation_manager: CancellationContextManager,
        logger: Logger,
    ):
        super().__init__(logger=logger)
        self._resource_config = resource_config
        self._reservation_info = reservation_info
        self._cs_api = cs_api
        self._cancellation_manager = cancellation_manager
        self._rollback_manager = RollbackCommandsManager(logger=self._logger)
        self._on_task_progress = on_task_progress_check_if_cancelled(
            cancellation_manager
        )

        self.generate_name = NameGenerator(max_length=80)

    def _validate_deploy_app(self, deploy_app: VMFromTerraformGit):
        """Terraform plan."""

        pass


    def _prepare_vm_details_data(
        self, deployed_vm, deploy_app: VMFromTerraformGit
    ) -> VmDetailsData:
        """Prepare CloudShell VM Details model."""
        pass

    def _create_vm(
        self,
        deploy_app: VMFromTerraformGit,
        vm_name: str,
        vm_resource_pool,
        vm_storage,
        vm_folder,
        dc
    ):
        """Create VM on the TF."""
        pass

    def _prepare_app_attrs(
        self, deploy_app: VMFromTerraformGit, vm: VmHandler
    ) -> list[Attribute]:
        attrs = []

        link_attr = get_deploy_app_vm_console_link_attr(
            deploy_app, self._resource_config, vm, vm.si
        )
        if link_attr:
            attrs.append(link_attr)

        return attrs

    def _prepare_deploy_app_result(
        self,
        tf_handler: TerraformCPHandler,
        deploy_app: VMFromTerraformGit,
        vm_name: str,
    ) -> DeployAppResult:
        vm_details_data = self._prepare_vm_details_data(
            deployed_vm=tf_handler,
            deploy_app=deploy_app,
        )
        tf_proc_executer = ObjectFactory.create_tf_proc_executer(self._config,
                                                                 sandbox_data_handler,
                                                                 shell_helper,
                                                                 tf_working_dir)
        self._logger.info(f"Prepared VM details: {vm_details_data}")

        return DeployAppResult(
            actionId=deploy_app.actionId,
            vmUuid=tf_handler.uuid,
            vmName=vm_name,
            vmDetailsData=vm_details_data,
            deployedAppAdditionalData={
                "ip_regex": deploy_app.ip_regex,
                "refresh_ip_timeout": deploy_app.refresh_ip_timeout,
                "auto_power_off": deploy_app.auto_power_off,
                "auto_delete": deploy_app.auto_delete,
            },
            deployedAppAttributes=self._prepare_app_attrs(deploy_app, tf_handler),
        )

    def _deploy(self, request_actions: DeployVMRequestActions) -> DeployAppResult:
        """Deploy TF VM."""
        conf = self._resource_config
        # noinspection PyTypeChecker
        deploy_app: VMFromTerraformGit = request_actions.deploy_app

        with self._cancellation_manager:
            self._validate_deploy_app(deploy_app)

        if deploy_app.autogenerated_name:
            vm_name = self.generate_name(deploy_app.app_name)
        else:
            vm_name = deploy_app.app_name

        self._logger.info(f"Generated name for the VM: {vm_name}")

        with self._rollback_manager:
            try:
                tf_proc_executer = ObjectFactory.create_tf_proc_executer(self._config,
                                                                         sandbox_data_handler,
                                                                         shell_helper,
                                                                         tf_working_dir)
                if tf_proc_executer.can_execute_run():
                    self._provider_handler.initialize_provider(shell_helper)
                    tf_proc_executer.init_terraform()
                    tf_proc_executer.tag_terraform()
                    tf_proc_executer.plan_terraform()
                    tf_proc_executer.apply_terraform()
                    tf_proc_executer.save_terraform_outputs()
                else:
                    self._handle_error_output(shell_helper,
                                              "This Terraform Module has been successfully deployed but "
                                              "destroy failed. Please destroy successfully before running "
                                              "execute again.")
            finally:
                if self._using_remote_state(shell_helper):
                    LocalDir.delete_local_temp_dir(sandbox_data_handler, tf_working_dir)

        self._logger.info(f"Preparing Deploy App result for the {deployed_vm}")
        return self._prepare_deploy_app_result(
            tf_handler=deployed_vm,
            deploy_app=deploy_app,
            vm_name=vm_name,
        )
