# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push or pull request events
on: 
  push:    
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          cd package
          echo "Installing requirements.txt and test_requirements.txt:"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
      - name: Lint with flake8
        run: |
            pwd
            python -m pip install flake8
            # stop the build if there are Python syntax errors or undefined names
            # E722 bare 'except'
            # W605 invalid escape sequence '\.'
            # E501 line too long
            # F841 local variable 'e' is assigned to but never used
            python -m flake8 . --count --ignore=E722,W605,E501,F841 --exclude=*__init__.py,*tag_terraform_resources.py,*data_model.py --statistics --show-source

      - name: Create package and install it
        run: |
          python -m pip install --upgrade pip
          chmod +x ci_deploy.sh
          ./ci_deploy.sh
      - name: Test unit tests with unittest
        run: |
          python -m unittest
      - name: Test integration tests for shells/generic_terraform_service with unittest
        env:
          AZUREAPP_TF_INPUTS: ${{ secrets.AZUREAPP_TF_INPUTS }}
          GH_TF_PRIVATE_AZUREAPP_URL: ${{ secrets.GITHUB_TF_PRIVATE_AZUREAPP_URL }}
          GH_TOKEN_DEC: ${{ secrets.GITHUB_TOKEN_DEC }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_APPLICATION_ID: ${{ secrets.AZURE_APPLICATION_ID }}
          AZURE_APPLICATION_KEY_DEC: ${{ secrets.AZURE_APPLICATION_KEY_DEC }}
        run: |
          echo "##############################"
          echo "GH_TF_PRIVATE_AZUREAPP_URL = $GH_TF_PRIVATE_AZUREAPP_URL"
          echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
          echo "$GITHUB_CONTEXT"
          echo "##############################"
          pwd
          cd package/tests/integration_tests
          pwd
          python -m unittest discover -p "int_test_mock*.py"
