# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          cd package
          echo "Installing requirements.txt and test_requirements.txt:"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
      - name: Lint with flake8
        run: |
            pwd
            python -m pip install flake8
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --ignore=F632 /shells/generic_terraform_service/src/data_model.py /shells/backends/azure_tf_backend/src/data_model.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create package and install it
        run: |
          python -m pip install --upgrade pip
          chmod +x ci_deploy.sh
          ./ci_deploy.sh
      - name: Test with unittest
        run: |
          python -m unittest

